application: 4s-hatos
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: css/favicon.ico
  upload: css/favicon.ico
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: .*
  script: main.py
