application: 4s-hatos
version: 1
runtime: python
api_version: 1

skip_files:
- ^jquery-mobile/*
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
handlers:
- url: /favicon.ico
  static_files: css/favicon.ico
  upload: css/favicon.ico
- url: /jegyzetek
  static_dir: jegyzetek
- url: /img
  static_dir: img
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: .*
  script: main.py
